import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from '@/utils/providers';
import { Menu } from '@/components/Menu/Menu';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<head>
				<link
					rel='stylesheet'
					href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css'
				/>
			</head>
			<body className={`${inter.className} bg-[#0d0d0d]`}>
				<Menu />
				<main className='p-4'>
					<Providers>{children}</Providers>
				</main>
			</body>
		</html>
	);
}
